[[main]]
    name = "Downloads"
    weight = 20
    url = "/downloads/"
[[main]]
    parent = "Downloads"
    name = "jLibBig"
    url = "/libbig/"
    weight = 31
[[main]]
    parent = "Downloads"
    name = "Distributed subgraph isomorphism"
    url = "/distributed-subgraph-isomorphism/"
    weight = 32
